name: Cypress Cloud
# npx cypress run --record --key 7470fa9f-01b7-46df-b5fc-9640c6d04366
on:
  workflow_dispatch: 
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*

jobs:
  cypress-e2e-electron:
    runs-on: ubunto-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{  github.event.inputs.spec  }}
        env:
          CYPRESS_RECORD_KEY: 7470fa9f-01b7-46df-b5fc-9640c6d04366
          GITHUB_TOKEN: ${{  secrets.GITHUB_TOKEN  }}

  cypress-e2e-chrome:
    needs: cypress-e2e-electron
    runs-on: ubunto-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install-command: yarn install
          browser: chrome
          record: true
          group: UI Chrome
          spec: ${{  github.event.inputs.spec  }}
        env:
          CYPRESS_RECORD_KEY: 7470fa9f-01b7-46df-b5fc-9640c6d04366
          GITHUB_TOKEN: ${{  secrets.GITHUB_TOKEN  }}

  cypress-e2e-firefox:
    needs: cypress-e2e-chrome
    runs-on: ubunto-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install-command: yarn install
          browser: firefox
          record: true
          group: UI Firefox
          spec: ${{  github.event.inputs.spec  }}
        env:
          CYPRESS_RECORD_KEY: 7470fa9f-01b7-46df-b5fc-9640c6d04366
          GITHUB_TOKEN: ${{  secrets.GITHUB_TOKEN  }}
